### Forest Cover Type in Roosevelt National Forest in colorado

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('covtype.csv')

In [3]:
df

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,...,0,0,0,0,0,0,0,0,0,3
581008,2391,152,19,67,12,95,240,237,119,845,...,0,0,0,0,0,0,0,0,0,3
581009,2386,159,17,60,7,90,236,241,130,854,...,0,0,0,0,0,0,0,0,0,3
581010,2384,170,15,60,5,90,230,245,143,864,...,0,0,0,0,0,0,0,0,0,3
581011,2383,165,13,60,4,67,231,244,141,875,...,0,0,0,0,0,0,0,0,0,3

In [4]:
df['Cover_Type'].value_counts()

2    283301
1    211840
3     35754
7     20510
6     17367
5      9493
4      2747
Name: Cover_Type, dtype: int64

In [5]:
import sklearn.model_selection as ml
import sklearn.tree as tree
import sklearn.metrics as metrices

#### Train test split

In [6]:
y=df.Cover_Type
x=df.drop('Cover_Type',axis=1)

In [7]:
print(y.shape,x.shape)

(581012,) (581012, 54)

In [8]:
x_train,x_test,y_train,y_test=ml.train_test_split(x,y,random_state=1)

#### Model building

In [9]:
x_train

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
95831,3096,44,14,270,27,3425,222,210,119,5004,...,0,0,0,0,0,0,0,0,0,0
526980,3050,99,19,270,25,2430,247,210,84,1710,...,0,0,0,0,0,0,0,0,0,0
67626,2926,139,14,511,13,3757,241,235,120,4201,...,0,0,0,0,0,0,0,0,0,0
54382,2968,203,12,582,59,6067,214,250,170,5516,...,0,0,0,0,0,0,0,0,0,0
63127,3267,17,10,722,62,3401,212,219,144,4251,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371403,3288,353,13,417,77,3439,196,216,157,2698,...,1,0,0,0,0,0,0,0,0,0
491263,3075,140,14,240,-6,866,240,235,122,1237,...,0,0,0,0,0,0,0,0,0,0
470924,3095,84,7,0,0,1167,230,228,131,2140,...,0,0,0,0,0,0,0,0,0,0
491755,2889,64,9,218,84,685,229,221,125,930,...,0,0,1,0,0,0,0,0,0,0
128037,2771,27,11,0,0,1880,215,217,137,2089,...,0,0,0,0,0,0,0,0,0,0

In [10]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 435759 entries, 95831 to 128037
Data columns (total 54 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   Elevation                           435759 non-null  int64
 1   Aspect                              435759 non-null  int64
 2   Slope                               435759 non-null  int64
 3   Horizontal_Distance_To_Hydrology    435759 non-null  int64
 4   Vertical_Distance_To_Hydrology      435759 non-null  int64
 5   Horizontal_Distance_To_Roadways     435759 non-null  int64
 6   Hillshade_9am                       435759 non-null  int64
 7   Hillshade_Noon                      435759 non-null  int64
 8   Hillshade_3pm                       435759 non-null  int64
 9   Horizontal_Distance_To_Fire_Points  435759 non-null  int64
 10  Wilderness_Area1                    435759 non-null  int64
 11  Wilderness_Area2                    435759 non-null  int64
 12  Wilderness_Area3                    435759 non-null  int64
 13  Wilderness_Area4                    435759 non-null  int64
 14  Soil_Type1                          435759 non-null  int64
 15  Soil_Type2                          435759 non-null  int64
 16  Soil_Type3                          435759 non-null  int64
 17  Soil_Type4                          435759 non-null  int64
 18  Soil_Type5                          435759 non-null  int64
 19  Soil_Type6                          435759 non-null  int64
 20  Soil_Type7                          435759 non-null  int64
 21  Soil_Type8                          435759 non-null  int64
 22  Soil_Type9                          435759 non-null  int64
 23  Soil_Type10                         435759 non-null  int64
 24  Soil_Type11                         435759 non-null  int64
 25  Soil_Type12                         435759 non-null  int64
 26  Soil_Type13                         435759 non-null  int64
 27  Soil_Type14                         435759 non-null  int64
 28  Soil_Type15                         435759 non-null  int64
 29  Soil_Type16                         435759 non-null  int64
 30  Soil_Type17                         435759 non-null  int64
 31  Soil_Type18                         435759 non-null  int64
 32  Soil_Type19                         435759 non-null  int64
 33  Soil_Type20                         435759 non-null  int64
 34  Soil_Type21                         435759 non-null  int64
 35  Soil_Type22                         435759 non-null  int64
 36  Soil_Type23                         435759 non-null  int64
 37  Soil_Type24                         435759 non-null  int64
 38  Soil_Type25                         435759 non-null  int64
 39  Soil_Type26                         435759 non-null  int64
 40  Soil_Type27                         435759 non-null  int64
 41  Soil_Type28                         435759 non-null  int64
 42  Soil_Type29                         435759 non-null  int64
 43  Soil_Type30                         435759 non-null  int64
 44  Soil_Type31                         435759 non-null  int64
 45  Soil_Type32                         435759 non-null  int64
 46  Soil_Type33                         435759 non-null  int64
 47  Soil_Type34                         435759 non-null  int64
 48  Soil_Type35                         435759 non-null  int64
 49  Soil_Type36                         435759 non-null  int64
 50  Soil_Type37                         435759 non-null  int64
 51  Soil_Type38                         435759 non-null  int64
 52  Soil_Type39                         435759 non-null  int64
 53  Soil_Type40                         435759 non-null  int64
dtypes: int64(54)
memory usage: 182.9 MB

In [11]:
x_train['Soil_Type1'].value_counts()

0    433518
1      2241
Name: Soil_Type1, dtype: int64

In [12]:
x_train['Wilderness_Area4'].value_counts()

0    408099
1     27660
Name: Wilderness_Area4, dtype: int64

In [13]:
x_train.describe()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
count,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000,...,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000,435759.000000
mean,2959.577489,155.749462,14.107516,269.358650,46.492525,2350.292944,212.144316,223.341742,142.548289,1982.608676,...,0.044027,0.090344,0.077786,0.002738,0.003261,0.000211,0.000521,0.026673,0.023830,0.015068
std,279.808192,111.876032,7.491361,212.372396,58.325182,1557.875504,26.791468,19.754864,38.304472,1325.347851,...,0.205155,0.286674,0.267835,0.052252,0.057012,0.014529,0.022818,0.161126,0.152518,0.121823
min,1859.000000,0.000000,0.000000,0.000000,-173.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2810.000000,58.000000,9.000000,108.000000,7.000000,1106.000000,198.000000,213.000000,119.000000,1024.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2996.000000,127.000000,13.000000,218.000000,30.000000,1998.000000,218.000000,226.000000,143.000000,1711.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3163.000000,261.000000,18.000000,384.000000,69.000000,3329.000000,231.000000,237.000000,168.000000,2550.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,3858.000000,360.000000,66.000000,1397.000000,601.000000,7112.000000,254.000000,254.000000,254.000000,7173.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
for i in range(1,40):
    for j in range(i,41):
        if sum(x_train['Soil_Type'+str(i)]*x_train['Soil_Type'+str(j)])==0:
            pass
        else:
            print(sum(x_train['Soil_Type'+str(i)]*x_train['Soil_Type'+str(j)]))

2241
5663
3598
9322
1201
4946
76
135
859
24342
9277
22472
13166
452
2
2163
2570
1432
3043
6946
612
24937
43375
15996
339
1938
783
729
86514
22675
19185
39368
33896
1193
1421
92
227
11623
10384

In [15]:
xtrain,xval,ytrain,yval=ml.train_test_split(x_train,y_train)

In [16]:
algo1=tree.DecisionTreeClassifier()
algo1.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [17]:
algo1.score(xtrain,ytrain)

1.0

In [18]:
algo1.score(xval,yval)

0.9269414356526529

In [19]:
algo1.get_depth()

41

In [25]:
a=np.arange(35,43)
testscore=np.zeros(len(a))
trainscore=np.zeros(len(a))
for i in range(len(a)):
    algo1=tree.DecisionTreeClassifier(max_depth=a[i])
    algo1.fit(xtrain,ytrain)
    trainscore[i]=algo1.score(xtrain,ytrain)
    testscore[i]=algo1.score(xval,yval)
print(trainscore,testscore)

[0.99979499 0.99989903 0.99994798 0.99997552 0.99999082 0.99999388
 1.         1.        ] [0.92694144 0.92622545 0.926868   0.92693226 0.92647329 0.92634478
 0.9268221  0.92662934]

Best tree is with max_depth=38

In [26]:
algo1=tree.DecisionTreeClassifier(max_depth=38)
algo1.fit(xtrain,ytrain)
algo1.score(xval,yval)

0.9267853864512575

### Results

In [27]:
y_pred=algo1.predict(x_test)

In [28]:
from sklearn import metrics as mts
mts.confusion_matrix(y_test,y_pred)

array([[49049,  3538,     5,     0,    79,    13,   253],
       [ 3458, 66520,   219,     3,   349,   185,    47],
       [    5,   219,  8315,    74,    21,   375,     0],
       [    0,     1,    92,   564,     0,    28,     0],
       [   51,   420,    21,     0,  1852,     8,     0],
       [   10,   156,   369,    33,    16,  3784,     0],
       [  293,    30,     0,     0,     3,     0,  4795]], dtype=int64)

In [30]:
report=mts.classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           1       0.93      0.93      0.93     52937
           2       0.94      0.94      0.94     70781
           3       0.92      0.92      0.92      9009
           4       0.84      0.82      0.83       685
           5       0.80      0.79      0.79      2352
           6       0.86      0.87      0.86      4368
           7       0.94      0.94      0.94      5121

    accuracy                           0.93    145253
   macro avg       0.89      0.89      0.89    145253
weighted avg       0.93      0.93      0.93    145253

Decent f1-scores are acheved